[package]
name = "chacha"
version = "1.0.1"
description = "An implementation of ChaCha20 & Poly1305 stream cipher"
repository = "https://github.com/Demali-876/Chacha20-Poly1305"
keywords = [ "encryption", "decryption", "aead", "poly1305", "chacha20" ]
license = "MIT"

[dependencies]
base = "0.14.7"
vector = "0.4.1"

[dev-dependencies]
bench = "1.0.0"
test = "2.1.1"

[toolchain]
moc = "0.14.11"