[package]
name = "chacha20-poly1305"
version = "1.0.0"
description = ""
repository = "https://github.com/Demali-876/json"
keywords = [ "json", "parse", "stringfy", "validate" ]
license = "MIT"

[dependencies]
base = "0.14.7"
vector = "0.4.1"

[dev-dependencies]
bench = "1.0.0"
test = "2.1.1"

[toolchain]
moc = "0.14.11"